version: "3.8"
services:
  go:
    container_name: "devexcel-excel-api"
    environment:
      - APP_ENV=dev
      - PORT=8080
      - HOST=http://localhost
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"