version: "3.8"
services:
  go:
    container_name: "devexcel-excel-generator-api"
    environment:
      - ENV=DOCKER
      - PORT=8080
      - HOST=
      - STORAGE=./storage
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"